import { Injectable } from '@nestjs/common';
import {
  ReportFieldI,
  ReportImageI,
  ReportSectionI,
  VehicleReportI,
} from './report.types';

@Injectable()
export class ReportTemplateService {
  render(report: VehicleReportI) {
    const completedSections = report.sections.filter(
      (section) => section.fields.length > 0 || section.images.length > 0,
    );

    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${this.escape(report.vehicle.name)} report</title>
    <style>${this.styles()}</style>
  </head>
  <body>
    <main>
      ${this.renderCover(report, completedSections.length)}
      ${this.renderOverview(report)}
      ${completedSections.map((section, index) => this.renderSection(section, index)).join('')}
    </main>
  </body>
</html>`;
  }

  renderHeaderTemplate(report: VehicleReportI) {
    return `
      <style>
        .report-header { width: 100%; padding: 0 30px; font-family: Arial, sans-serif; font-size: 9px; color: #667085; display: flex; justify-content: space-between; }
      </style>
      <div class="report-header">
        <span>${this.escape(report.vehicle.vehicleNumber)}</span>
        <span>Vehicle Evaluation Report</span>
      </div>
    `;
  }

  renderFooterTemplate() {
    return `
      <style>
        .report-footer { width: 100%; padding: 0 30px; font-family: Arial, sans-serif; font-size: 9px; color: #667085; display: flex; justify-content: space-between; }
      </style>
      <div class="report-footer">
        <span>Generated by Car Report</span>
        <span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span>
      </div>
    `;
  }

  private renderCover(report: VehicleReportI, sectionCount: number) {
    return `
      <section class="cover page">
        <div class="cover-topline">
          <span>Vehicle Evaluation</span>
          <span>${this.escape(this.formatDate(report.generatedAt))}</span>
        </div>
        <div class="cover-hero">
          <div>
            <p class="eyebrow">Inspection report</p>
            <h1>${this.escape(report.vehicle.name)}</h1>
            <p class="vehicle-number">${this.escape(report.vehicle.vehicleNumber)}</p>
          </div>
          <div class="status-pill">${this.escape(this.formatStatus(report.vehicle.status))}</div>
        </div>
        <div class="cover-grid">
          <div class="cover-card">
            <span>Model</span>
            <strong>${this.escape(report.vehicle.model)}</strong>
          </div>
          <div class="cover-card">
            <span>Evaluator</span>
            <strong>${this.escape(report.vehicle.evaluator)}</strong>
          </div>
          <div class="cover-card">
            <span>Sections with data</span>
            <strong>${sectionCount}</strong>
          </div>
          <div class="cover-card">
            <span>Last updated</span>
            <strong>${this.escape(this.formatDate(report.vehicle.updatedAt))}</strong>
          </div>
        </div>
        <div class="cover-band">
          <div class="car-mark">
            <div class="car-roof"></div>
            <div class="car-body"></div>
            <div class="wheel wheel-left"></div>
            <div class="wheel wheel-right"></div>
          </div>
          <div>
            <p class="band-title">Structured condition summary</p>
            <p class="band-copy">Only completed fields and available inspection images are included in this report.</p>
          </div>
        </div>
      </section>
    `;
  }

  private renderOverview(report: VehicleReportI) {
    return `
      <section class="overview page-section">
        <div class="section-heading">
          <span>01</span>
          <div>
            <h2>Report Overview</h2>
            <p>High level details captured from the completed evaluation.</p>
          </div>
        </div>
        <div class="metric-grid">
          ${report.metrics
            .map(
              (metric) => `
                <div class="metric">
                  <span>${this.escape(metric.label)}</span>
                  <strong>${this.escape(metric.value)}</strong>
                </div>
              `,
            )
            .join('')}
        </div>
      </section>
    `;
  }

  private renderSection(section: ReportSectionI, index: number) {
    return `
      <section class="report-section page-section">
        <div class="section-heading">
          <span>${String(index + 2).padStart(2, '0')}</span>
          <div>
            <h2>${this.escape(section.name)}</h2>
            ${section.description ? `<p>${this.escape(section.description)}</p>` : ''}
          </div>
        </div>
        ${section.fields.length > 0 ? this.renderFields(section.fields) : ''}
        ${section.images.length > 0 ? this.renderImages(section.images) : ''}
      </section>
    `;
  }

  private renderFields(fields: ReportFieldI[]) {
    return `
      <div class="field-grid">
        ${fields
          .map(
            (field) => `
              <div class="field-row">
                <span>${this.escape(field.label)}</span>
                <strong>${this.escape(field.value)}</strong>
              </div>
            `,
          )
          .join('')}
      </div>
    `;
  }

  private renderImages(images: ReportImageI[]) {
    return `
      <div class="image-section">
        <h3>Inspection Images</h3>
        <div class="image-grid">
          ${images
            .map(
              (image) => `
                <figure class="image-card">
                  ${
                    image.dataUrl
                      ? `<img src="${image.dataUrl}" alt="${this.escape(image.label)}" />`
                      : `<div class="image-fallback">${this.escape(image.fallbackText || 'Image unavailable')}</div>`
                  }
                  <figcaption>
                    <strong>${this.escape(image.label)}</strong>
                    <span>${this.escape(image.originalName)}</span>
                  </figcaption>
                </figure>
              `,
            )
            .join('')}
        </div>
      </div>
    `;
  }

  private styles() {
    return `
      * { box-sizing: border-box; }
      html { color: #101828; font-family: Arial, Helvetica, sans-serif; font-size: 13px; line-height: 1.45; }
      body { margin: 0; background: #ffffff; }
      main { width: 100%; }
      .page { min-height: 100vh; page-break-after: always; padding: 46px 42px; }
      .page-section { padding: 18px 42px 26px; page-break-inside: avoid; }
      .cover { background: linear-gradient(135deg, #111827 0%, #172554 46%, #0f766e 100%); color: #ffffff; display: flex; flex-direction: column; justify-content: space-between; }
      .cover-topline { align-items: center; color: rgba(255,255,255,0.72); display: flex; font-size: 11px; justify-content: space-between; letter-spacing: 0.08em; text-transform: uppercase; }
      .cover-hero { align-items: flex-start; display: flex; gap: 24px; justify-content: space-between; margin-top: 74px; }
      .eyebrow { color: #67e8f9; font-size: 12px; font-weight: 700; letter-spacing: 0.12em; margin: 0 0 10px; text-transform: uppercase; }
      h1 { font-size: 44px; letter-spacing: 0; line-height: 1.02; margin: 0; max-width: 520px; }
      .vehicle-number { color: rgba(255,255,255,0.8); font-size: 20px; margin: 16px 0 0; }
      .status-pill { background: rgba(255,255,255,0.14); border: 1px solid rgba(255,255,255,0.32); border-radius: 999px; font-size: 12px; font-weight: 700; padding: 9px 14px; text-transform: uppercase; white-space: nowrap; }
      .cover-grid { display: grid; gap: 14px; grid-template-columns: repeat(4, 1fr); margin-top: 64px; }
      .cover-card { background: rgba(255,255,255,0.12); border: 1px solid rgba(255,255,255,0.18); border-radius: 8px; min-height: 92px; padding: 16px; }
      .cover-card span { color: rgba(255,255,255,0.68); display: block; font-size: 11px; margin-bottom: 12px; text-transform: uppercase; }
      .cover-card strong { display: block; font-size: 18px; line-height: 1.18; }
      .cover-band { align-items: center; background: rgba(255,255,255,0.95); border-radius: 8px; color: #101828; display: grid; gap: 22px; grid-template-columns: 180px 1fr; margin-top: 72px; padding: 24px; }
      .band-title { font-size: 20px; font-weight: 800; margin: 0 0 4px; }
      .band-copy { color: #475467; margin: 0; }
      .car-mark { height: 80px; position: relative; }
      .car-roof { background: #0e7490; border-radius: 60px 70px 0 0; height: 35px; left: 42px; position: absolute; top: 12px; width: 96px; }
      .car-body { background: #14b8a6; border-radius: 15px 28px 12px 12px; height: 34px; left: 18px; position: absolute; top: 38px; width: 146px; }
      .wheel { background: #111827; border: 5px solid #f8fafc; border-radius: 50%; height: 30px; position: absolute; top: 55px; width: 30px; }
      .wheel-left { left: 42px; }
      .wheel-right { right: 38px; }
      .section-heading { align-items: flex-start; border-bottom: 1px solid #e4e7ec; display: grid; gap: 14px; grid-template-columns: 42px 1fr; margin-bottom: 18px; padding-bottom: 13px; }
      .section-heading > span { align-items: center; background: #0f766e; border-radius: 8px; color: #ffffff; display: flex; font-size: 12px; font-weight: 800; height: 34px; justify-content: center; width: 34px; }
      h2 { font-size: 22px; letter-spacing: 0; line-height: 1.15; margin: 0; }
      .section-heading p { color: #667085; margin: 5px 0 0; }
      .metric-grid { display: grid; gap: 12px; grid-template-columns: repeat(3, 1fr); }
      .metric { background: #f8fafc; border: 1px solid #e4e7ec; border-radius: 8px; min-height: 76px; padding: 14px; page-break-inside: avoid; }
      .metric span, .field-row span { color: #667085; display: block; font-size: 11px; font-weight: 700; margin-bottom: 6px; text-transform: uppercase; }
      .metric strong { display: block; font-size: 18px; }
      .field-grid { display: grid; gap: 10px; grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .field-row { background: #ffffff; border: 1px solid #e4e7ec; border-left: 4px solid #14b8a6; border-radius: 8px; min-height: 68px; padding: 12px 14px; page-break-inside: avoid; }
      .field-row strong { color: #101828; display: block; font-size: 13px; font-weight: 700; overflow-wrap: anywhere; white-space: pre-wrap; }
      .image-section { margin-top: 20px; }
      h3 { color: #344054; font-size: 14px; letter-spacing: 0.04em; margin: 0 0 12px; text-transform: uppercase; }
      .image-grid { display: grid; gap: 14px; grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .image-card { border: 1px solid #d0d5dd; border-radius: 8px; margin: 0; overflow: hidden; page-break-inside: avoid; }
      .image-card img { background: #f2f4f7; display: block; height: 220px; object-fit: cover; width: 100%; }
      .image-fallback { align-items: center; background: #f2f4f7; color: #667085; display: flex; font-weight: 700; height: 220px; justify-content: center; padding: 20px; text-align: center; }
      figcaption { background: #ffffff; border-top: 1px solid #e4e7ec; padding: 10px 12px; }
      figcaption strong { display: block; font-size: 13px; margin-bottom: 3px; }
      figcaption span { color: #667085; display: block; font-size: 11px; overflow-wrap: anywhere; }
      @media print {
        .report-section { break-inside: avoid; }
        .field-row, .metric, .image-card { break-inside: avoid; }
      }
    `;
  }

  private formatDate(date: Date) {
    return new Intl.DateTimeFormat('en-IN', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    }).format(date);
  }

  private formatStatus(status: string) {
    return status
      .split(/[\s_-]+/)
      .filter(Boolean)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join(' ');
  }

  private escape(value: string | number) {
    return String(value)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#039;');
  }
}
