export const FIELD_SUBGROUPS: Record<string, Record<string, string>> = {
  basic: {
    seller_full_name: 'Seller Info',
    seller_address: 'Seller Info',
    seller_phone: 'Seller Info',
    seller_email: 'Seller Info',

    registered: 'Registration Details',
    registration_number: 'Registration Details',
    car_brand: 'Registration Details',
    engine_number: 'Registration Details',
    chassis_number_available: 'Registration Details',
    chassis_number_value: 'Registration Details',
    rc_owner_name: 'Registration Details',
    rc_owner_phone: 'Registration Details',
    registration_state: 'Registration Details',
    registered_rto: 'Registration Details',
    duplicate_key: 'Registration Details',
    rc_availability: 'Registration Details',

    manufacturing_year: 'Vehicle Specs & Dates',
    car_model: 'Vehicle Specs & Dates',
    fuel_type: 'Vehicle Specs & Dates',
    transmission_type: 'Vehicle Specs & Dates',
    car_variant: 'Vehicle Specs & Dates',
    ownership_number: 'Vehicle Specs & Dates',
    kms_driven: 'Vehicle Specs & Dates',
    sell_time: 'Vehicle Specs & Dates',
    date_of_registration: 'Vehicle Specs & Dates',
    registration_validity: 'Vehicle Specs & Dates',
    tax_validity: 'Vehicle Specs & Dates',
    vehicle_location: 'Vehicle Specs & Dates',
    engine_cc: 'Vehicle Specs & Dates',
    engine_cc_other: 'Vehicle Specs & Dates',
    number_of_cylinders: 'Vehicle Specs & Dates',
    vehicle_usage: 'Vehicle Specs & Dates',
    body_type: 'Vehicle Specs & Dates',
    seating_capacity: 'Vehicle Specs & Dates',

    customer_price: 'Condition & Pricing',
    odometer_working: 'Condition & Pricing',
    odometer_reading: 'Condition & Pricing',
    accidental: 'Condition & Pricing',
    oem_warranty: 'Condition & Pricing',
    oem_months_remaining: 'Condition & Pricing',
    oem_kms_remaining: 'Condition & Pricing',
    basic_remarks: 'Condition & Pricing',
  },
  documents: {
    rc_front_image: 'Registration Certificate (RC)',
    rc_back_image: 'Registration Certificate (RC)',
    inter_state_transfer: 'Registration Certificate (RC)',
    chassis_impression_image: 'Registration Certificate (RC)',
    rc_mismatch: 'Registration Certificate (RC)',
    rc_mismatch_remarks: 'Registration Certificate (RC)',

    insurance_type: 'Insurance Policy',
    insurance_validity: 'Insurance Policy',
    insurance_company: 'Insurance Policy',
    insurance_idv: 'Insurance Policy',
    insurance_image: 'Insurance Policy',
    ncb: 'Insurance Policy',
    ncb_percentage: 'Insurance Policy',
    insurance_mismatch: 'Insurance Policy',

    under_hypothecation: 'Finance & RTO Details',
    hypothecation_bank_name: 'Finance & RTO Details',
    loan_status: 'Finance & RTO Details',
    loan_noc: 'Finance & RTO Details',
    loan_noc_image: 'Finance & RTO Details',
    form_35: 'Finance & RTO Details',
    form_35_image: 'Finance & RTO Details',
    rto_noc_issued: 'Finance & RTO Details',

    document_remarks: 'Document Remarks (Select all that apply)',
  },
  exterior: {
    tyre_front_rhs: 'Tyre Condition (Tread Remaining)',
    tyre_rear_rhs: 'Tyre Condition (Tread Remaining)',
    spare_wheel: 'Tyre Condition (Tread Remaining)',
    tyre_rear_lhs: 'Tyre Condition (Tread Remaining)',
    tyre_front_lhs: 'Tyre Condition (Tread Remaining)',

    missing_parts: 'Macro Status',
    full_body_repaint: 'Macro Status',
  },
  engine: {
    engine_compartment_image: 'Engine & Mechanical Overview',
    engine_sound: 'Engine & Mechanical Overview',
    engine_condition: 'Engine & Mechanical Overview',
    engine_condition_image: 'Engine & Mechanical Overview',
    smoke: 'Engine & Mechanical Overview',
    engine_idle_start_video: 'Engine & Mechanical Overview',
    battery: 'Engine & Mechanical Overview',
    battery_image: 'Engine & Mechanical Overview',
    radiator: 'Engine & Mechanical Overview',
    starting_motor: 'Engine & Mechanical Overview',
    coolant: 'Engine & Mechanical Overview',
    blowby_back_compression: 'Engine & Mechanical Overview',
    blowby_back_compression_image: 'Engine & Mechanical Overview',
    silencer: 'Engine & Mechanical Overview',
    silencer_image: 'Engine & Mechanical Overview',
    clutch_operations: 'Engine & Mechanical Overview',
    clutch_operations_image: 'Engine & Mechanical Overview',
    engine_oil: 'Engine & Mechanical Overview',
    engine_oil_image: 'Engine & Mechanical Overview',
    turbo_charger: 'Engine & Mechanical Overview',
    turbo_charger_image: 'Engine & Mechanical Overview',
    engine_mount: 'Engine & Mechanical Overview',
    engine_mount_image: 'Engine & Mechanical Overview',
    sump: 'Engine & Mechanical Overview',
    sump_image: 'Engine & Mechanical Overview',

    gearbox: 'Final Notes & Gearbox',
    gearbox_image: 'Final Notes & Gearbox',
    gearbox_leakage: 'Final Notes & Gearbox',
    engine_comments: 'Final Notes & Gearbox',
  },
  interior_electrical: {
    cluster_panel: 'Cabin Overview Media',
    cluster_panel_image: 'Cabin Overview Media',
    warning_details: 'Cabin Overview Media',
    dashboard: 'Cabin Overview Media',
    dashboard_image: 'Cabin Overview Media',
    front_seat: 'Cabin Overview Media',
    rear_seat: 'Cabin Overview Media',
    roof_lining: 'Cabin Overview Media',
    roof_lining_image: 'Cabin Overview Media',
    inside_rear_view_mirror: 'Cabin Overview Media',
    inside_rear_view_mirror_image: 'Cabin Overview Media',
    interior_rear_to_dash_image: 'Cabin Overview Media',
    power_window_panel_image: 'Cabin Overview Media',
    push_button: 'Cabin Overview Media',
    dashboard_switches: 'Cabin Overview Media',
    power_window_lock: 'Cabin Overview Media',
    hand_brake: 'Cabin Overview Media',
    car_electrical: 'Cabin Overview Media',
    car_electrical_image: 'Cabin Overview Media',
    cng_lpg_kit_image: 'Cabin Overview Media',
    second_key: 'Cabin Overview Media',
    platform: 'Cabin Overview Media',
    platform_image: 'Cabin Overview Media',
  },
  test_drive: {
    steering_system: 'Driving Configuration',
    steering_adjustment: 'Driving Configuration',
    steering_audio_control: 'Driving Configuration',
    cruise_control: 'Driving Configuration',
    seat_adjustment: 'Driving Configuration',

    steering_wheel: 'Dynamic Performance',
    suspension_system: 'Dynamic Performance',
    brakes: 'Dynamic Performance',
    clutch_system: 'Dynamic Performance',
    transmission_automatic: 'Dynamic Performance',
    vehicle_horn: 'Dynamic Performance',
  },
  features: {
    keyless_entry: 'Amenities & Safety',
    keyless_entry_image: 'Amenities & Safety',
    stereo: 'Amenities & Safety',
    stereo_image: 'Amenities & Safety',
    stereo_brand: 'Amenities & Safety',
    rear_parking_sensor: 'Amenities & Safety',
    sunroof: 'Amenities & Safety',
    sunroof_image: 'Amenities & Safety',
    gps_navigation: 'Amenities & Safety',
    alloy_wheels: 'Amenities & Safety',
    alloy_wheels_image: 'Amenities & Safety',
    fog_lamps_feature: 'Amenities & Safety',
    air_bag: 'Amenities & Safety',
    air_bag_image: 'Amenities & Safety',
    seat_belt: 'Amenities & Safety',
    abs_ebd: 'Amenities & Safety',
    abs_ebd_image: 'Amenities & Safety',
    glove_box: 'Amenities & Safety',
    glove_box_image: 'Amenities & Safety',
    interior_modifications: 'Amenities & Safety',
  },
  air_conditioning: {
    ac_working: 'HVAC System Status',
    ac_cooling: 'HVAC System Status',
    heater: 'HVAC System Status',
    climate_control: 'HVAC System Status',
    ac_condenser_compressor: 'HVAC System Status',
    ac_filter_damaged: 'HVAC System Status',
    ac_blower_grill: 'HVAC System Status',
    rear_defogger: 'HVAC System Status',
  },
};
