ALTER TABLE "form_fields" ADD COLUMN "subgroup" TEXT;

UPDATE "document_groups"
SET "name" = 'Basic Details'
WHERE "identifier" = 'basic'
  AND "type" = 'FORM_STEP';

UPDATE "form_fields"
SET "subgroup" = NULL;

WITH subgroup_map("identifier", "field_key", "subgroup") AS (
    VALUES
    ('basic', 'seller_full_name', 'Seller Info'),
    ('basic', 'seller_address', 'Seller Info'),
    ('basic', 'seller_phone', 'Seller Info'),
    ('basic', 'seller_email', 'Seller Info'),
    ('basic', 'registered', 'Registration Details'),
    ('basic', 'registration_number', 'Registration Details'),
    ('basic', 'car_brand', 'Registration Details'),
    ('basic', 'engine_number', 'Registration Details'),
    ('basic', 'chassis_number_available', 'Registration Details'),
    ('basic', 'chassis_number_value', 'Registration Details'),
    ('basic', 'rc_owner_name', 'Registration Details'),
    ('basic', 'rc_owner_phone', 'Registration Details'),
    ('basic', 'registration_state', 'Registration Details'),
    ('basic', 'registered_rto', 'Registration Details'),
    ('basic', 'duplicate_key', 'Registration Details'),
    ('basic', 'rc_availability', 'Registration Details'),
    ('basic', 'manufacturing_year', 'Vehicle Specs & Dates'),
    ('basic', 'car_model', 'Vehicle Specs & Dates'),
    ('basic', 'fuel_type', 'Vehicle Specs & Dates'),
    ('basic', 'transmission_type', 'Vehicle Specs & Dates'),
    ('basic', 'car_variant', 'Vehicle Specs & Dates'),
    ('basic', 'ownership_number', 'Vehicle Specs & Dates'),
    ('basic', 'kms_driven', 'Vehicle Specs & Dates'),
    ('basic', 'sell_time', 'Vehicle Specs & Dates'),
    ('basic', 'date_of_registration', 'Vehicle Specs & Dates'),
    ('basic', 'registration_validity', 'Vehicle Specs & Dates'),
    ('basic', 'tax_validity', 'Vehicle Specs & Dates'),
    ('basic', 'vehicle_location', 'Vehicle Specs & Dates'),
    ('basic', 'engine_cc', 'Vehicle Specs & Dates'),
    ('basic', 'engine_cc_other', 'Vehicle Specs & Dates'),
    ('basic', 'number_of_cylinders', 'Vehicle Specs & Dates'),
    ('basic', 'vehicle_usage', 'Vehicle Specs & Dates'),
    ('basic', 'body_type', 'Vehicle Specs & Dates'),
    ('basic', 'seating_capacity', 'Vehicle Specs & Dates'),
    ('basic', 'customer_price', 'Condition & Pricing'),
    ('basic', 'odometer_working', 'Condition & Pricing'),
    ('basic', 'odometer_reading', 'Condition & Pricing'),
    ('basic', 'accidental', 'Condition & Pricing'),
    ('basic', 'oem_warranty', 'Condition & Pricing'),
    ('basic', 'oem_months_remaining', 'Condition & Pricing'),
    ('basic', 'oem_kms_remaining', 'Condition & Pricing'),
    ('basic', 'basic_remarks', 'Condition & Pricing'),
    ('documents', 'rc_front_image', 'Registration Certificate (RC)'),
    ('documents', 'rc_back_image', 'Registration Certificate (RC)'),
    ('documents', 'inter_state_transfer', 'Registration Certificate (RC)'),
    ('documents', 'chassis_impression_image', 'Registration Certificate (RC)'),
    ('documents', 'rc_mismatch', 'Registration Certificate (RC)'),
    ('documents', 'rc_mismatch_remarks', 'Registration Certificate (RC)'),
    ('documents', 'insurance_type', 'Insurance Policy'),
    ('documents', 'insurance_validity', 'Insurance Policy'),
    ('documents', 'insurance_company', 'Insurance Policy'),
    ('documents', 'insurance_idv', 'Insurance Policy'),
    ('documents', 'insurance_image', 'Insurance Policy'),
    ('documents', 'ncb', 'Insurance Policy'),
    ('documents', 'ncb_percentage', 'Insurance Policy'),
    ('documents', 'insurance_mismatch', 'Insurance Policy'),
    ('documents', 'under_hypothecation', 'Finance & RTO Details'),
    ('documents', 'hypothecation_bank_name', 'Finance & RTO Details'),
    ('documents', 'loan_status', 'Finance & RTO Details'),
    ('documents', 'loan_noc', 'Finance & RTO Details'),
    ('documents', 'loan_noc_image', 'Finance & RTO Details'),
    ('documents', 'form_35', 'Finance & RTO Details'),
    ('documents', 'form_35_image', 'Finance & RTO Details'),
    ('documents', 'rto_noc_issued', 'Finance & RTO Details'),
    ('documents', 'document_remarks', 'Document Remarks (Select all that apply)'),
    ('exterior', 'tyre_front_rhs', 'Tyre Condition (Tread Remaining)'),
    ('exterior', 'tyre_rear_rhs', 'Tyre Condition (Tread Remaining)'),
    ('exterior', 'spare_wheel', 'Tyre Condition (Tread Remaining)'),
    ('exterior', 'tyre_rear_lhs', 'Tyre Condition (Tread Remaining)'),
    ('exterior', 'tyre_front_lhs', 'Tyre Condition (Tread Remaining)'),
    ('exterior', 'missing_parts', 'Macro Status'),
    ('exterior', 'full_body_repaint', 'Macro Status'),
    ('engine', 'engine_compartment_image', 'Engine & Mechanical Overview'),
    ('engine', 'engine_sound', 'Engine & Mechanical Overview'),
    ('engine', 'engine_condition', 'Engine & Mechanical Overview'),
    ('engine', 'engine_condition_image', 'Engine & Mechanical Overview'),
    ('engine', 'smoke', 'Engine & Mechanical Overview'),
    ('engine', 'engine_idle_start_video', 'Engine & Mechanical Overview'),
    ('engine', 'battery', 'Engine & Mechanical Overview'),
    ('engine', 'battery_image', 'Engine & Mechanical Overview'),
    ('engine', 'radiator', 'Engine & Mechanical Overview'),
    ('engine', 'starting_motor', 'Engine & Mechanical Overview'),
    ('engine', 'coolant', 'Engine & Mechanical Overview'),
    ('engine', 'blowby_back_compression', 'Engine & Mechanical Overview'),
    ('engine', 'blowby_back_compression_image', 'Engine & Mechanical Overview'),
    ('engine', 'silencer', 'Engine & Mechanical Overview'),
    ('engine', 'silencer_image', 'Engine & Mechanical Overview'),
    ('engine', 'clutch_operations', 'Engine & Mechanical Overview'),
    ('engine', 'clutch_operations_image', 'Engine & Mechanical Overview'),
    ('engine', 'engine_oil', 'Engine & Mechanical Overview'),
    ('engine', 'engine_oil_image', 'Engine & Mechanical Overview'),
    ('engine', 'turbo_charger', 'Engine & Mechanical Overview'),
    ('engine', 'turbo_charger_image', 'Engine & Mechanical Overview'),
    ('engine', 'engine_mount', 'Engine & Mechanical Overview'),
    ('engine', 'engine_mount_image', 'Engine & Mechanical Overview'),
    ('engine', 'sump', 'Engine & Mechanical Overview'),
    ('engine', 'sump_image', 'Engine & Mechanical Overview'),
    ('engine', 'gearbox', 'Final Notes & Gearbox'),
    ('engine', 'gearbox_image', 'Final Notes & Gearbox'),
    ('engine', 'gearbox_leakage', 'Final Notes & Gearbox'),
    ('engine', 'engine_comments', 'Final Notes & Gearbox'),
    ('interior_electrical', 'cluster_panel', 'Cabin Overview Media'),
    ('interior_electrical', 'cluster_panel_image', 'Cabin Overview Media'),
    ('interior_electrical', 'warning_details', 'Cabin Overview Media'),
    ('interior_electrical', 'dashboard', 'Cabin Overview Media'),
    ('interior_electrical', 'dashboard_image', 'Cabin Overview Media'),
    ('interior_electrical', 'front_seat', 'Cabin Overview Media'),
    ('interior_electrical', 'rear_seat', 'Cabin Overview Media'),
    ('interior_electrical', 'roof_lining', 'Cabin Overview Media'),
    ('interior_electrical', 'roof_lining_image', 'Cabin Overview Media'),
    ('interior_electrical', 'inside_rear_view_mirror', 'Cabin Overview Media'),
    ('interior_electrical', 'inside_rear_view_mirror_image', 'Cabin Overview Media'),
    ('interior_electrical', 'interior_rear_to_dash_image', 'Cabin Overview Media'),
    ('interior_electrical', 'power_window_panel_image', 'Cabin Overview Media'),
    ('interior_electrical', 'push_button', 'Cabin Overview Media'),
    ('interior_electrical', 'dashboard_switches', 'Cabin Overview Media'),
    ('interior_electrical', 'power_window_lock', 'Cabin Overview Media'),
    ('interior_electrical', 'hand_brake', 'Cabin Overview Media'),
    ('interior_electrical', 'car_electrical', 'Cabin Overview Media'),
    ('interior_electrical', 'car_electrical_image', 'Cabin Overview Media'),
    ('interior_electrical', 'cng_lpg_kit_image', 'Cabin Overview Media'),
    ('interior_electrical', 'second_key', 'Cabin Overview Media'),
    ('interior_electrical', 'platform', 'Cabin Overview Media'),
    ('interior_electrical', 'platform_image', 'Cabin Overview Media'),
    ('test_drive', 'steering_system', 'Driving Configuration'),
    ('test_drive', 'steering_adjustment', 'Driving Configuration'),
    ('test_drive', 'steering_audio_control', 'Driving Configuration'),
    ('test_drive', 'cruise_control', 'Driving Configuration'),
    ('test_drive', 'seat_adjustment', 'Driving Configuration'),
    ('test_drive', 'steering_wheel', 'Dynamic Performance'),
    ('test_drive', 'suspension_system', 'Dynamic Performance'),
    ('test_drive', 'brakes', 'Dynamic Performance'),
    ('test_drive', 'clutch_system', 'Dynamic Performance'),
    ('test_drive', 'transmission_automatic', 'Dynamic Performance'),
    ('test_drive', 'vehicle_horn', 'Dynamic Performance'),
    ('features', 'keyless_entry', 'Amenities & Safety'),
    ('features', 'keyless_entry_image', 'Amenities & Safety'),
    ('features', 'stereo', 'Amenities & Safety'),
    ('features', 'stereo_image', 'Amenities & Safety'),
    ('features', 'stereo_brand', 'Amenities & Safety'),
    ('features', 'rear_parking_sensor', 'Amenities & Safety'),
    ('features', 'sunroof', 'Amenities & Safety'),
    ('features', 'sunroof_image', 'Amenities & Safety'),
    ('features', 'gps_navigation', 'Amenities & Safety'),
    ('features', 'alloy_wheels', 'Amenities & Safety'),
    ('features', 'alloy_wheels_image', 'Amenities & Safety'),
    ('features', 'fog_lamps_feature', 'Amenities & Safety'),
    ('features', 'air_bag', 'Amenities & Safety'),
    ('features', 'air_bag_image', 'Amenities & Safety'),
    ('features', 'seat_belt', 'Amenities & Safety'),
    ('features', 'abs_ebd', 'Amenities & Safety'),
    ('features', 'abs_ebd_image', 'Amenities & Safety'),
    ('features', 'glove_box', 'Amenities & Safety'),
    ('features', 'glove_box_image', 'Amenities & Safety'),
    ('features', 'interior_modifications', 'Amenities & Safety'),
    ('air_conditioning', 'ac_working', 'HVAC System Status'),
    ('air_conditioning', 'ac_cooling', 'HVAC System Status'),
    ('air_conditioning', 'heater', 'HVAC System Status'),
    ('air_conditioning', 'climate_control', 'HVAC System Status'),
    ('air_conditioning', 'ac_condenser_compressor', 'HVAC System Status'),
    ('air_conditioning', 'ac_filter_damaged', 'HVAC System Status'),
    ('air_conditioning', 'ac_blower_grill', 'HVAC System Status'),
    ('air_conditioning', 'rear_defogger', 'HVAC System Status')
)
UPDATE "form_fields" AS ff
SET "subgroup" = subgroup_map."subgroup"
FROM subgroup_map
JOIN "document_groups" AS dg
  ON dg."identifier" = subgroup_map."identifier"
WHERE ff."document_group_id" = dg."id"
  AND ff."field_key" = subgroup_map."field_key";
